version: '3.3'

services:

  faythe_web:
    container_name: faythe_web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
        #ports:
        #- '3001:3000'
    network_mode: 'host'
    environment:
      - NODE_ENV=development
