version: '3.3'

services:

  faythe_web:
    container_name: faythe_web
    image: 10.240.201.50:8891/react_faythe:latest
    volumes:
      - '.:/app'
      - '/app/node_modules'
        #ports:
        #- '3001:3000'
    network_mode: 'host'
    environment:
      - NODE_ENV=development
